
name: add_dockerhub

on:
  workflow_run:
    workflows:
      - "go build&test"
    types:
      - "completed"



jobs:
  add_dockerhub:
   runs-on: ubuntu-latest

   steps:
     - uses: actions/checkout@v3
       
     - name: Build and push docker image
       uses: docker/build-push-action@v1
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
         repository: artur9022/goapps
         dockerfile: artur9022/goapp
         tags: latest


