#
name: Go versia
on:
  workflow_dispatch:
    inputs:
      GOversion:
        description: 'GoVersion'
        required: true
        default: '1.15.15'
        type: choice
        options:
        - 1.18.8
        - 1.15.15
        - 1.18.6

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "GoVersion: $GOVERSION"
          env: GOVERSION ${{ inputs.GOversion }}

