#
#
#
name: Use_matrix

on: [push]

jobs:
  Use_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [1.19.3. 1.18.9, 1.13]
    runs-on: ${{ matrix.os}}

    steps:
          - uses: actions/checkout@v3

          - name: Set up go
            uses: actions/setup-go@v3
            with:
              go-version: ${{ matrix.version }}

          - name: Build
            run:  go build -v ./...

          - name: Test
            run:  go test -v ./..../



